"""Re-export hub for backward compatibility.

All ``from bot.keyboards.inline import <name>`` statements across the codebase
continue to work unchanged.  New code should import directly from the relevant
sub-module (e.g. ``from bot.keyboards.admin import get_admin_keyboard``).
"""
from __future__ import annotations

from bot.keyboards.admin import (
    get_button_emoji_mode_keyboard,
    get_admin_analytics_keyboard,
    get_admin_intervals_keyboard,
    get_admin_keyboard,
    get_admin_router_keyboard,
    get_admin_settings_menu_keyboard,
    get_broadcast_cancel_keyboard,
    get_chart_preview_keyboard,
    get_chart_render_mode_keyboard,
    get_debounce_keyboard,
    get_growth_keyboard,
    get_growth_registration_keyboard,
    get_growth_stage_keyboard,
    get_ip_interval_keyboard,
    get_maintenance_keyboard,
    get_pause_menu_keyboard,
    get_pause_message_keyboard,
    get_pause_type_keyboard,
    get_refresh_cooldown_keyboard,
    get_restart_confirm_keyboard,
    get_schedule_interval_keyboard,
    get_users_menu_keyboard,
)
from bot.keyboards.channel import (
    get_channel_connect_confirm_keyboard,
    get_channel_menu_keyboard,
    get_channel_pending_confirm_keyboard,
    get_channel_replace_confirm_keyboard,
)
from bot.keyboards.common import (
    E_ADMIN,
    E_ALERTS,
    E_BACK,
    E_BELL,
    E_BOT_NOTIF,
    E_BOT_SETTINGS,
    E_CANCEL,
    E_CHANGE_IP,
    E_CHANNEL,
    E_CHANNEL_SECTION,
    E_CHECK,
    E_CONFIRM_CHANGE,
    E_DELETE_DATA,
    E_DELETE_IP,
    E_DISCUSS,
    E_ERROR_PING,
    E_FACT,
    E_FAQ,
    E_HELP,
    E_HOURGLASS,
    E_INSTR_HELP,
    E_INSTRUCTION,
    E_IP,
    E_IP_ADDR,
    E_IP_SECTION,
    E_IP_SETTINGS,
    E_MENU,
    E_NEWS,
    E_NOTIF_SECTION,
    E_OFFLINE,
    E_ONLINE,
    E_PAUSE_CHANNEL,
    E_PING_CHECK,
    E_PING_FAIL,
    E_PING_LOADING,
    E_QUEUE,
    E_REFRESH,
    E_REGION,
    E_REPLY,
    E_RESUME,
    E_SCHEDULE,
    E_SCHEDULE_CHANGES,
    E_SCHEDULE_SEC,
    E_SETTINGS,
    E_STATS,
    E_SUCCESS,
    E_SUPPORT,
    E_TIMER,
    E_WARN,
    E_WELCOME,
    _btn,
    _nav_row,
    _url_btn,
    _url_btn_with_emoji,
    get_error_keyboard,
    get_understood_keyboard,
)
from bot.keyboards.format import (
    get_format_power_keyboard,
    get_format_schedule_keyboard,
    get_format_settings_keyboard,
    get_test_publication_keyboard,
)
from bot.keyboards.help import (
    get_faq_keyboard,
    get_help_keyboard,
    get_instruction_section_keyboard,
    get_instructions_keyboard,
    get_support_keyboard,
)
from bot.keyboards.ip import (
    get_ip_change_confirm_keyboard,
    get_ip_delete_confirm_keyboard,
    get_ip_deleted_keyboard,
    get_ip_management_keyboard,
    get_ip_monitoring_keyboard_no_ip,
    get_ip_ping_error_keyboard,
    get_ip_ping_fail_keyboard,
    get_ip_ping_result_keyboard,
    get_ip_saved_fail_keyboard,
    get_ip_saved_keyboard,
    get_ip_saved_success_keyboard,
)
from bot.keyboards.main_menu import (
    get_main_menu,
    get_restoration_keyboard,
    get_statistics_keyboard,
)
from bot.keyboards.notifications import (
    get_channel_notification_keyboard,
    get_notification_main_keyboard,
    get_notification_reminders_keyboard,
    get_notification_select_keyboard,
    get_notification_target_select_keyboard,
    get_notification_targets_keyboard,
    get_reminder_keyboard,
)
from bot.keyboards.schedule import get_schedule_view_keyboard
from bot.keyboards.settings import (
    get_cleanup_keyboard,
    get_deactivate_confirm_keyboard,
    get_delete_data_confirm_keyboard,
    get_delete_data_final_keyboard,
    get_settings_keyboard,
)
from bot.keyboards.wizard import (
    get_confirm_keyboard,
    get_queue_keyboard,
    get_region_keyboard,
    get_wizard_bot_notification_keyboard,
    get_wizard_channel_notification_keyboard,
    get_wizard_notify_target_keyboard,
)

__all__ = [
    # common helpers & emoji constants
    "_btn",
    "_url_btn",
    "_url_btn_with_emoji",
    "_nav_row",
    "E_ADMIN",
    "E_ALERTS",
    "E_BACK",
    "E_BELL",
    "E_BOT_NOTIF",
    "E_BOT_SETTINGS",
    "E_CANCEL",
    "E_CHANGE_IP",
    "E_CHANNEL",
    "E_CHANNEL_SECTION",
    "E_CHECK",
    "E_CONFIRM_CHANGE",
    "E_DELETE_DATA",
    "E_DELETE_IP",
    "E_DISCUSS",
    "E_ERROR_PING",
    "E_FACT",
    "E_FAQ",
    "E_HELP",
    "E_HOURGLASS",
    "E_INSTR_HELP",
    "E_INSTRUCTION",
    "E_IP",
    "E_IP_ADDR",
    "E_IP_SECTION",
    "E_IP_SETTINGS",
    "E_MENU",
    "E_NEWS",
    "E_NOTIF_SECTION",
    "E_OFFLINE",
    "E_ONLINE",
    "E_PAUSE_CHANNEL",
    "E_PING_CHECK",
    "E_PING_FAIL",
    "E_PING_LOADING",
    "E_QUEUE",
    "E_REFRESH",
    "E_REGION",
    "E_REPLY",
    "E_RESUME",
    "E_SCHEDULE",
    "E_SCHEDULE_CHANGES",
    "E_SCHEDULE_SEC",
    "E_SETTINGS",
    "E_STATS",
    "E_SUCCESS",
    "E_SUPPORT",
    "E_TIMER",
    "E_WARN",
    "E_WELCOME",
    "get_error_keyboard",
    "get_understood_keyboard",
    # main_menu
    "get_main_menu",
    "get_restoration_keyboard",
    "get_statistics_keyboard",
    # wizard
    "get_region_keyboard",
    "get_queue_keyboard",
    "get_confirm_keyboard",
    "get_wizard_notify_target_keyboard",
    "get_wizard_bot_notification_keyboard",
    "get_wizard_channel_notification_keyboard",
    # notifications
    "get_reminder_keyboard",
    "get_notification_main_keyboard",
    "get_notification_reminders_keyboard",
    "get_notification_targets_keyboard",
    "get_notification_target_select_keyboard",
    "get_notification_select_keyboard",
    "get_channel_notification_keyboard",
    # channel
    "get_channel_pending_confirm_keyboard",
    "get_channel_connect_confirm_keyboard",
    "get_channel_replace_confirm_keyboard",
    "get_channel_menu_keyboard",
    # settings
    "get_settings_keyboard",
    "get_cleanup_keyboard",
    "get_delete_data_confirm_keyboard",
    "get_delete_data_final_keyboard",
    "get_deactivate_confirm_keyboard",
    # schedule
    "get_schedule_view_keyboard",
    # help
    "get_help_keyboard",
    "get_faq_keyboard",
    "get_support_keyboard",
    "get_instructions_keyboard",
    "get_instruction_section_keyboard",
    # ip
    "get_ip_monitoring_keyboard_no_ip",
    "get_ip_management_keyboard",
    "get_ip_change_confirm_keyboard",
    "get_ip_delete_confirm_keyboard",
    "get_ip_deleted_keyboard",
    "get_ip_saved_keyboard",
    "get_ip_saved_success_keyboard",
    "get_ip_saved_fail_keyboard",
    "get_ip_ping_result_keyboard",
    "get_ip_ping_fail_keyboard",
    "get_ip_ping_error_keyboard",
    # format
    "get_format_settings_keyboard",
    "get_format_schedule_keyboard",
    "get_format_power_keyboard",
    "get_test_publication_keyboard",
    # admin
    "get_admin_keyboard",
    "get_admin_analytics_keyboard",
    "get_admin_settings_menu_keyboard",
    "get_button_emoji_mode_keyboard",
    "get_chart_render_mode_keyboard",
    "get_chart_preview_keyboard",
    "get_refresh_cooldown_keyboard",
    "get_maintenance_keyboard",
    "get_admin_intervals_keyboard",
    "get_schedule_interval_keyboard",
    "get_ip_interval_keyboard",
    "get_debounce_keyboard",
    "get_pause_menu_keyboard",
    "get_pause_type_keyboard",
    "get_pause_message_keyboard",
    "get_growth_keyboard",
    "get_growth_stage_keyboard",
    "get_growth_registration_keyboard",
    "get_restart_confirm_keyboard",
    "get_users_menu_keyboard",
    "get_admin_router_keyboard",
    "get_broadcast_cancel_keyboard",
]
